spring:
  application:
    name: romanticmessenger

server:
  port: 8080

claude:
  api:
    key: ${CLAUDE_API_KEY}
  model:
    version: ${CLAUDE_MODEL}
  max-tokens: ${CLAUDE_MAX_TOKENS}
  timeout:
    seconds: ${CLAUDE_TIMEOUT_SECONDS:60}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_POLLY_REGION:eu-west-1}
  s3:
    region: ${AWS_S3_REGION:eu-north-1}
    bucket-name: ${AWS_S3_BUCKET_NAME}


